### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by HoBeom** [leimao/ONNX-Runtime-Inference#2]
Thank you for making a good docker file.
I was able to successfully build onnx-runtime and build a video parallel test pipeline using sample code (develop branch).
However, an error occurred in CUDA runtime. My HOST computer is 11.0 version, so should I build 11.0 accordingly?

error bellow
`2021-03-24 14:21:39.688310246 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running Clip node. Name:'Clip_3' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
terminate called after throwing an instance of 'Ort::Exception'
  what():  Non-zero status code returned while running Clip node. Name:'Clip_3' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
[1]    29002 abort (core dumped)  ./build/src/inference_camera --use_cuda`

**Comment by leimao** [comment]
Hi @HoBeom the development branch is not ready for release yet. Could you please try the main branch using a CUDA 11 Docker container? You can just replace the [base container](docker pull nvcr.io/nvidia/cuda:11.2.1-cudnn8-devel-ubuntu20.04) in my Dockerfile to something like `nvcr.io/nvidia/cuda:11.2.1-cudnn8-devel-ubuntu20.04`. All the available CUDA Docker base container could be found at https://ngc.nvidia.com/catalog/containers/nvidia:cuda/tags

**Comment by HoBeom** [comment]
Thank you. I'll try. And I'll let you know the results.

**Comment by HoBeom** [comment]
CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find CUDA: Found unsuitable version "10.2", but required is exact
  version "11.1" (found /usr/local/cuda)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:580 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.19/Modules/FindCUDA.cmake:1121 (find_package_handle_standard_args)
  /usr/lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  CMakeLists.txt:7 (find_package)

I got this error and try to fix. but fail to run on cuda

**Comment by HoBeom** [comment]
I've tried many things but all failed, the cuda of the Host OS seems to be the problem. Thank you for your help.

**Comment by fcakyon** [comment]
@HoBeom refer to my fork for RTX3000 series and CUDA 11.2 support of this repo: https://github.com/fcakyon/ONNX-Runtime-Inference/tree/cuda11

**Comment by leimao** [comment]
> I've tried many things but all failed, the cuda of the Host OS seems to be the problem. Thank you for your help.

@HoBeom I got the similar problem when I was upgrading the ONNX-Runtime and the CUDA Runtime Library. This can be fixed with upgrading the CMake to the latest version. I will post my updates shortly.

**Comment by HoBeom** [comment]
thank you!!

**Comment by leimao** [comment]
> thank you!! @leimao

The update is already on the master branch. ONNX-Runtime 1.8 also changed the interface slightly. You could see the implementation changes in the commits.
